server {
    listen 8080;
    server_name localhost;

    # 1. A root kiemelése a server blokkba, hogy az Nginx globálisan lássa a mappastruktúrát
    root /usr/share/nginx/html;
    index index.html index.htm;

    port_in_redirect off;
    absolute_redirect off;

    location / {
        # 2. Közvetlenül a mappa index.html fájlját töltjük be, megkerülve az Nginx belső redirectjét
        try_files $uri $uri/index.html /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
