server {
    listen 8080;
    server_name localhost;

    # Megakadályozza, hogy az Nginx a belső portot (8080) tegye az átirányítás URL-jébe
    port_in_redirect off;
    absolute_redirect off;

    include /etc/nginx/mime.types;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # 1. Ha a kérés egy létező mappa (pl. /docs), de nincs a végén '/'
        # akkor manuálisan dobunk egy helyes, relatív 301-es átirányítást
        if (-d $request_filename) {
            rewrite ^([^.\?]*[^/])$ $1/ permanent;
        }

        # 2. Útvonal keresése
        try_files $uri $uri/ $uri/index.html =404;
    }

    # Statikus fájlok kiszolgálása (CSS, JS, képek)
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
